### ISSUE TITLE
tried and failed

### ISSUE THREAD

**Issue by SeJohnEff** [LordEidi/hifiberryos_hacks#1]
Hi, I tried . Didn't follow your description. I suppose with copy you use scp?
Running Hifiberry OS on a Raspberry Pi3

this is how I did (paste from the repository)

nano run_radio.sh
chmod +x run_radio.sh
nano /etc/systemd/system/autoplay_radio.service
nano /library/playlists/radio.m3u
systemctl enable autoplay_radio.service
#Created symlink /etc/systemd/system/default.target.wants/autoplay_radio.service → /etc/systemd/system/autoplay_radio.service.

It works

**Comment by LordEidi** [comment]
Not sure what I should answer tbh. Do you run a somewhat recent version of Hifiberry OS? What's in those files you opened with nano? Is the bash script executable? Is the mpd service running at all? Any errors in the logs? What happens if you execute the bash script by hand after your system boots?

**Comment by SeJohnEff** [comment]
Do you run a somewhat recent version of Hifiberry OS? Yes, latest available
What's in those files you opened with nano? Is the bash script executable? Is the mpd service running at all? Any errors in the logs? What happens if you execute the bash script by hand after your system boots?

**Comment by SeJohnEff** [comment]
Thank you for the kind reply.
I must have done several mistakes.
It works!

I got inspired so I created a timer for daily reboot. That is something I need since I want to listen to same radio channel every morning but might have played something else during the day.

https://github.com/SeJohnEff/hifiberryOS_rebooter

**Comment by LordEidi** [comment]
Great to hear! And glad to help. I am closing this issue then.
